
on:
  push:
    branches:
      - dev-frontend
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        working-directory: PaymentFrontend
        run: |
          npm install
          npm run build --if-present
              
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
               
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
         app-name: 'app-payment-management-dev'
         slot-name: 'Production'
         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1B3AB76F8852468E80760028F566BAEA }}
         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
